AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template para el Sistema de Notificaciones Alertify'

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: AlertifyCriticalEvents

  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: AlertifyQueue
      VisibilityTimeout: 60
      MessageRetentionPeriod: 300

  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SQSQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "sqs:SendMessage"
            Resource: !GetAtt SQSQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref SNSTopic

  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopic
      Protocol: sqs
      Endpoint: !GetAtt SQSQueue.Arn