name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name alertify-stack \
            --capabilities CAPABILITY_IAM \
            --region ${{ secrets.AWS_REGION }}

      - name: Notify on success
        if: success()
        run: |
          curl -X POST "https://api.sendgrid.com/v3/mail/send" \
            -H "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "personalizations": [{"to": [{"email": "${{ secrets.TO_EMAIL }}"}]}],
                  "from": {"email": "${{ secrets.FROM_EMAIL }}"},
                  "subject": "GitHub Actions Success - Alertify Project",
                  "content": [{"type": "text/plain", "value": "El despliegue a producción fue exitoso para el proyecto Alertify."}]
                }'

      - name: Notify on failure
        if: failure()
        run: |
          curl -X POST "https://api.sendgrid.com/v3/mail/send" \
            -H "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "personalizations": [{"to": [{"email": "${{ secrets.TO_EMAIL }}"}]}],
                  "from": {"email": "${{ secrets.FROM_EMAIL }}"},
                  "subject": "GitHub Actions Failure - Alertify Project",
                  "content": [{"type": "text/plain", "value": "El pipeline de GitHub Actions falló durante el despliegue del proyecto Alertify."}]
                }'