name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install aws-sdk
        run: npm install aws-sdk

      - name: Create a ZIP of the Lambda code
        run: |
          zip -r lambda-code.zip .

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name Alertify-Inc-ProcessEvents-Unique \
            --zip-file fileb://lambda-code.zip \
            --region ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name alertify-stack \
            --capabilities CAPABILITY_IAM \
            --region ${{ secrets.AWS_REGION }}

  notify_success:
    runs-on: ubuntu-latest
    if: success()
    needs: deploy
    steps:
      - name: Send success email notification
        run: |
          curl -X POST "https://api.sendgrid.com/v3/mail/send" \
            -H "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "personalizations": [{"to": [{"email": "${{ secrets.TO_EMAIL }}"}]}],
                  "from": {"email": "${{ secrets.FROM_EMAIL }}"},
                  "subject": "Deployment Successful - Alertify",
                  "content": [{"type": "text/plain", "value": "El despliegue fue exitoso en Alertify Inc."}]
                }'

  notify_failure:
    runs-on: ubuntu-latest
    if: failure()
    needs: deploy
    steps:
      - name: Send failure email notification
        run: |
          curl -X POST "https://api.sendgrid.com/v3/mail/send" \
            -H "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "personalizations": [{"to": [{"email": "${{ secrets.TO_EMAIL }}"}]}],
                  "from": {"email": "${{ secrets.FROM_EMAIL }}"},
                  "subject": "Deployment Failed - Alertify",
                  "content": [{"type": "text/plain", "value": "El pipeline falló durante el despliegue de Alertify Inc."}]
                }'