name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to AWS CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name alertify-stack \
            --capabilities CAPABILITY_IAM

  notify_failure:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Send email notification on failure
        run: |
          curl -X POST "https://api.sendgrid.com/v3/mail/send" \
            -H "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "personalizations": [{"to": [{"email": "tu-email@dominio.com"}]}],
                  "from": {"email": "from-email@dominio.com"},
                  "subject": "GitHub Actions Failure",
                  "content": [{"type": "text/plain", "value": "El pipeline de GitHub Actions falló."}]
                }'