name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip Lambda code
        run: zip lambda-code.zip index.js

      - name: Upload to S3
        run: |
          aws s3 cp lambda-code.zip s3://alertify-lambda-code-bucket-unique/lambda-code.zip

      - name: Deploy to CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name alertify-stack \
            --capabilities CAPABILITY_IAM \
            --region ${{ secrets.AWS_REGION }}