name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip Lambda code
        run: zip lambda-code.zip index.js

      - name: Upload Lambda code to S3
        run: |
          aws s3 cp lambda-code.zip s3://alertify-lambda-code-bucket-unique/lambda-code.zip

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name alertify-stack \
            --capabilities CAPABILITY_IAM

      - name: Notify on success
        if: success()
        run: |
          curl -X POST "https://api.sendgrid.com/v3/mail/send" \
            -H "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "personalizations": [{"to": [{"email": "${{ secrets.TO_EMAIL }}"}]}],
                  "from": {"email": "${{ secrets.FROM_EMAIL }}"},
                  "subject": "Deployment Successful - Alertify",
                  "content": [{"type": "text/plain", "value": "El despliegue fue exitoso en Alertify."}]
                }'

  notify_failure:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Notify on failure
        run: |
          curl -X POST "https://api.sendgrid.com/v3/mail/send" \
            -H "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "personalizations": [{"to": [{"email": "${{ secrets.TO_EMAIL }}"}]}],
                  "from": {"email": "${{ secrets.FROM_EMAIL }}"},
                  "subject": "Deployment Failed - Alertify",
                  "content": [{"type": "text/plain", "value": "El pipeline falló durante el despliegue de Alertify."}]
                }'
  notify_success:
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Send email notification on success
        run: |
          curl -X POST "https://api.sendgrid.com/v3/mail/send" \
            -H "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "personalizations": [{"to": [{"email": "${{ secrets.TO_EMAIL }}"}]}],
                  "from": {"email": "${{ secrets.FROM_EMAIL }}"},
                  "subject": "GitHub Actions Success - Alertify Project",
                  "content": [{"type": "text/plain", "value": "El pipeline de GitHub Actions completó el despliegue correctamente."}]
                }'